name: Repo Dispatcher
on:
  schedule:
    - cron: '30 21 * * *'
  workflow_dispatch:
    #ref: refs/heads/main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
        - name: Trigger Compile
          run: |
            curl \
            -X POST https://api.github.com/repos/${{ github.repository }}/actions/workflows/8056225/dispatches \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.workflow_token }}" \
            -d '{"ref": "main", "inputs": {RK3328 penWrt 19.07 Build.yml}}'
